Path fixes
elkowar/eww pull request #110
Opened 2021-02-07 15:37 UTC by undefinedDarkness

Please follow this template, if applicable.

## Description
Gives eww's scss parser enough rough info to find files from eww's config dir 

## Usage
```
@import "./colors.scss";
@import "colors.scss";
@use "./colors.scss";
@use "colors.scss";
```
These should be vaild.

### Showcase
![1612711927](https://user-images.githubusercontent.com/38278035/107151293-cca81100-6987-11eb-9497-bb2957780ce8.png)

## Additional Notes
This could be done more simply by asking grass to read the path directly but that would restrict eww's manipulation of the sass data, atm adding env args, I should note that wont work for imported files I think. Maybe fork the scss parser? maybe an easier solution idk

## Checklist

- [ ] All widgets I've added are correctly documented.
- [ ] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes. - not sure if this needs to be documented.
- [ ] I used `cargo fmt` to automatically format all code before committing - I commited that, hopefully that works

2021-02-07 15:38 UTC, undefinedDarkness commented
My git fork is a mess :disappointed_relieved:

2021-02-07 16:12 UTC, elkowar commented
In general, if you want to clean up the commit history, read up on interactive rebase (but make sure to backup your changes beforehand ^^)

I'll try out the changes soon! Regarding manipulating imported files, yea, that's actually kind of an issue i haven't yet considered. It might be worth seeing if grass would be willing to add a way for us to intercept into the import resolution, such that we could apply processing to the imported files manually. That's not directly related to this PR tho, so not a blocker

2021-02-07 16:22 UTC, elkowar commented
https://github.com/connorskees/grass/issues/46 Issue i filed on grass, for reference

2021-02-07 19:53 UTC, elkowar requested changes
Some slight changes, mainly error handling.
Errors shouldn't crash the whole application, but just be passed upwards. Thus, instead of `.expect` (which panics), use `.context` or `.with_context` (provided by `anyhow`) and ? - as I've done in the requested changes. Apart from the requests, everything looks good 👍🏻

2021-02-07 19:53 UTC, elkowar commented on src/util.rs
> +    grass_config = grass_config.load_path(config_dir);
```suggestion
    let grass_config = grass::Options::default().load_path(config_dir);
```

2021-02-07 19:53 UTC, elkowar commented on src/util.rs
> +    let file_content = replace_env_var_references(std::fs::read_to_string(path).expect("Given SCSS File Doesnt Exist!"));
```suggestion
    let config_dir = path.parent().context("given scss file does not have a parent directory")?;
    let scss_file_content =
        std::fs::read_to_string(path).with_context(|| format!("Given SCSS File Doesnt Exist! {}", path.display()))?;
    let file_content = replace_env_var_references(scss_file_content);
```

2021-02-07 19:53 UTC, elkowar commented on src/server.rs
> +    std::env::set_current_dir(&config_dir).expect("Failed to change working directory.");
```suggestion
    std::env::set_current_dir(&config_dir)
        .with_context(|| format!("Failed to set current working directory to {}", config_dir.display()))?;
```

2021-02-08 09:46 UTC, merged

2021-02-08 09:46 UTC, elkowar commented
Thanks!