Fix: the gtk `stack` widget bugfix
elkowar/eww pull request #1119
Opened 2024-06-18 00:28 UTC by ovalkonia

## Description

The `stack` widget was essentially useless, since the `:selected` property had no effect and resulted in a warning stating that a child with the given name wasn't found. This exact issue has already been described here ->  https://github.com/elkowar/eww/issues/1116.

I faced this problem trying to implement a clock that would change the format of the output on request. Also, I searched for configurations from other users that use this widget, but to no avail. It's as if nobody ever used it or something. Take a look at the following screenshot showing minimal configuration:
![1718663452](https://github.com/elkowar/eww/assets/60359793/37b34362-e241-4a84-b216-31a2803ab110)
As you can see, there's a warning and instead of the expected "1st", it shows "0th". It was tested under both Xorg and Wayland with the latest stable version of Eww from both github and AUR.

Looking at the code managing this widget, it appears that `gtk_widget.set_visible_child_name(&selected.to_string());` gets called before any of the actual children in the following match statement get added, which results in unexpected behaviour (easier to just check the diff).

## Usage

N/A

### Showcase

Here is that same minimal configuration from before, but this time using the fixed version:
![1718667805](https://github.com/elkowar/eww/assets/60359793/b2d459f4-752c-4e34-a851-33b3086040e9)
No warnings and it shows "1st", just as expected!

## Additional Notes

The very fact that this issue had gone unnoticed for almost four months seems reeeeeally weird to me, so maybe I'm just a dumbass. I have no idea how the stack widget worked in the showcase when it was added, since it seems like the issue was there from the very beginning. Anyway, let me know what you think!

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [x] All widgets I've added are correctly documented.
- [x] I added my changes to CHANGELOG.md, if appropriate.
- [x] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

2024-08-06 10:53 UTC, fabolous005 commented
Hi,
I'm also currently looking into the stack widget. So far with no luck.
I thought i could index the childs of the stack like this:
```yuck
(defvar stack-index 0)

(stack
	:selected stack-index
        (child-widget1)
        (child-widget2)
)
```
This would be extremely useful because you could update the variable from `on-hover` events from `eventbox`!
Do you know how to archive this or if it is even possible (yet)?

2024-08-06 11:43 UTC, ovalkonia commented
@fabolous005 Yeah, absolutely you can  can do that! `Eww` is quite flexible, the possibilities are endless. Try something like this:

```lisp
(defvar stack-index 0)

(eventbox
        :onhover "${EWW_CMD} update stack-index=${(stack-index + 1) % 3}"
        (stack
            :selected stack-index
            (label :text "first")
            (label :text "second")
            (label :text "third")
        )
 )
```

It's just a `stack` wrapped inside of an `eventbox`. If you hover over, it will switch to the next child.

You can update variables using `eww update variable=value`, and `EWW_CMD` is just a shortcut for the current running configuration (see https://elkowar.github.io/eww/magic-vars.html#eww_cmd).

For `eventbox` docs, see https://elkowar.github.io/eww/widgets.html#eventbox. Hope it helped!

2024-08-06 12:24 UTC, fabolous005 commented
Yeah, i tried that, but whatever i try i get the error `Child name '0' not found`, even with your exact example.
evv version: `eww 0.6.0 4d55e9ad63d1fae887726dffcd25a32def23d34f`

2024-08-06 12:30 UTC, ovalkonia commented
> Yeah, i tried that, but whatever i try i get the error `Child name '0' not found`, even with your exact example. evv version: `eww 0.6.0 4d55e9ad63d1fae887726dffcd25a32def23d34f`

Well, it is what it is for now, this pr solves this exact issue. Right now it essentially defaults to the `0th` child. If you update the variable, it will work since all the children will be there. Just ignore the error message and try hovering over it, it should work.

2024-08-24 08:23 UTC, w-lfchen requested changes
you can probably just apply this from the web interface
apart from this minor nitpick lgtm

2024-08-24 08:23 UTC, w-lfchen commented on crates/eww/src/widgets/widget_definitions.rs
> +    if let Ordering::Less = bargs.widget_use.children.len().cmp(&1) {
```suggestion
    if bargs.widget_use.children.len() < 1 {
```

2024-08-24 10:30 UTC, merged