Fix script vars being dumb
elkowar/eww pull request #40
Opened 2020-10-22 19:26 UTC by elkowar

This PR attempts to fix issues with script-var scripts not being closed correctly.

2020-10-22 19:27 UTC, elkowar commented
@buffet could you maybe look over this again? I'm really unsure if i understand all of this, and i'd want to make sure that it's now _done_ and no longer an issue ^^

2020-10-22 22:31 UTC, buffet commented
Remind me tomorrow.

2020-10-23 08:25 UTC, elkowar commented
@buffet there ya go, reminder here!

2020-10-23 15:10 UTC, buffet requested changes

2020-10-23 15:10 UTC, buffet commented on src/script_var_handler.rs
> +                    &[CString::new("sh")?, CString::new("-c")?, CString::new(command)?],
This should be /bin/sh.

2020-10-23 15:10 UTC, buffet commented on src/script_var_handler.rs
> +            nix::libc::kill(self.pid.as_raw(), libc::SIGTERM);
nix::sys::signal::kill takes the Pid newtype and is prolly what you should use here.

2020-10-23 16:00 UTC, elkowar commented
Thanks a ton, @buffet!

2020-10-23 16:01 UTC, buffet approved these changes

2020-10-23 16:03 UTC, merged