Add search and with functions for simple expressions
elkowar/eww pull request #407
Opened 2022-02-23 21:58 UTC by MartinJM

## Description

This PR adds a `search`, `captures`, and `with` function to the simple expressions.

- The `search` function will return all occurances of the regex. Return format is json, where the occurances are numbered.
- The `captures` function will return all captures of all the occurances of the regex. Return format is also json, but contains all capture groups separately.
- The `with` function allows for variables within simple expressions, which are only valid within the expression in the third argument.

The `search` and `capture` functions are so that there is less need for `grep` in `defpoll`s. This saves the creation of new processes.

The `with` function is mostly there because both the `search` and `captures` return multiple values (in a json object). To prevent having to do either multiple times to get multiple results, the `with` can be used.

## Usage

Simple examples:
```
search('abba', 'b')
{"0": "b", "1": "b"}

captures('abba', 'a(b)|ba')
{"0": {"0": "ab", "1": "b"}, "1": {"0": "ba"}}

with('a', '{"0": "hello ", "1": "world"}', 'a[0] + a[1]')
hello world
```

A real-world example in Eww (for volume):
```
(defwidget volume []
	(label
		:text "${ with('a', captures(master_volume, 'Left: .* \\[([[:digit:]]*%)\\] \\[(.*)\\]'), '(a[0][2] == \"off\"? \"Muted (\" : \"Volume: \") + a[0][1] + (a[0][2] == \"off\" ? \")\" : \"\")') }"
	)
)

(defpoll master_volume
	:interval "1s"
	:initial ""
	:run-while "true"
	`amixer sget Master`
)
```
Without the `with`, the whole `capture` would need to be in here 3 times.

## Additional Notes

If the `search` and `captures` functions are good enough for merging, but the `with` function is not, I can also make a separate PR for just them.

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [x] All widgets I've added are correctly documented.
- [x] I added my changes to CHANGELOG.md, if appropriate.
- [x] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

2022-02-24 00:11 UTC, MartinJM commented
I made a mistake in my code (empty search/captures don't work), so will be fixing that.

2022-02-24 00:32 UTC, MartinJM commented
Should be fixed now.

2022-02-24 12:22 UTC, viandoxdev commented
If you want you could also add the length function I made. There's a patch for it (on #394) but I didn't want to make a PR for just one function.

2022-02-24 13:40 UTC, MartinJM commented
Thank you for the replies!

> If you want you could also add the length function I made. There's a patch for it (on #394) but I didn't want to make a PR for just one function.

Oh cool, I'll add that as well when I have a little more time. I also implemented a hex decode function, which I'll probably add as well then.


> I definitely think the search and captures functions would be a great addition to the expression syntax. I'm not sure if I like the name `search`, then again I can't think of a better name currently ^^'

I agree that the name is not ideal, maybe `find` would be better?

> I think both of those functions should definitely use arrays over json objects as their return value, i.e. `captures("2020-12, 2021-01", "(\d\d\d\d)-(\d\d)")` should return `[["2020", "12"], ["2021", "01"]]`.

This does make more sense indeed. I will change that.

> While I think something like the `with` function is definitely a great addition, I'd argue it should probably rather be some new syntax, over having a function for that. a classic in many languages would be something along the lines of
> 
> ```
> let matches = search("foo bar baz", "f..") in matches[0]
> ```
> 
> That probably warrants a separate PR or feature by me, though ^^
> [...]
> I'll create a new feature request for the let-in syntax though, such that that can be tracked separately.

I'll remove the `with` function from this PR and add the information to the feature request, so that it can be discussed independently from the other functions.

> I currently don't really have much time for reviewing the code here (see the maintainance status section in the readme), so I can't guarantee that this will go super fast, I'm afraid.

No worries at all, and good luck with your thesis :+1:

2022-02-24 14:47 UTC, MartinJM commented
Sorry, I wanted to rename the branch, which should work, but apparently doesn't.

2022-02-24 16:21 UTC, MartinJM commented
@viandoxdev I've added the `length` function. I did change it so that it matches the `jq length` on objects as well.

2022-02-24 16:51 UTC, MartinJM commented
This now contains the following functions:
 - `search`
 - `capture`
 - `hex_decode`
 - `length`
 
 The output of the `search` and `captures` functions has changed to arrays.
 
 Examples:
 ```
 search('2020-12, 2021-01', '([[:digit:]]{4})-([[:digit:]]{2})')
 ["2020-12", "2021-01"]
 
 captures('2020-12, 2021-01', '([[:digit:]]{4})-([[:digit:]]{2})')
 [["2020-12", "2020", "12"], ["2021-01", "2021", "01"]]
 
 hex_decode('48656c6c6f')
 Hello
 
 length('abc')
 3
 
 length('[1, 2, 3]')
 3
 
 length('{"1": "1", "2": "2"}')
 2
 ```

2022-04-18 18:44 UTC, elkowar commented
Ok, finally getting back to this! Looks mostly good now!

I was just made aware of the fact that having `length` work on both strings and json is rather weird here, as that means that if you for some reason have a string that accidentally contains valid json somewhere where you expect a string, you'll get the wrong length.
For that reason, I'd say it'd be good to make this two functions, one called `str_length` and one called `json_length`, which would separate the two -- str_length treating everything as a text, even if it's valid json, and json_length erroring out when provided with invalid json


Also: What's the actual usecase of hex_decode? seems like an oddly specific, edgecase-y thing to add

2022-04-18 19:36 UTC, elkowar requested changes
In addition to the aforementioned changes to length, and me questioning the necessity of `hex_decode`, these would be some nicer ways to implement the search and captures functions

2022-04-18 19:36 UTC, elkowar commented on crates/simplexpr/src/eval.rs
> +                Ok(DynVal::from(retval))
```suggestion
                use serde_json::Value;
                let string = string.as_string()?;
                let pattern = regex::Regex::new(&pattern.as_string()?)?;
                Ok(Value::Array(
                    pattern
                        .captures_iter(&string)
                        .map(|captures| {
                            Value::Array(captures.iter().flatten().map(|x| Value::String(x.as_str().to_string())).collect())
                        })
                        .collect(),
                )
                .try_into()?)

```

2022-04-18 19:36 UTC, elkowar commented on crates/simplexpr/src/eval.rs
> +                Ok(DynVal::from(retval))
```suggestion
                use serde_json::Value;
                let string = string.as_string()?;
                let pattern = regex::Regex::new(&pattern.as_string()?)?;
                Ok(Value::Array(pattern.find_iter(&string).map(|x| Value::String(x.as_str().to_string())).collect())
                    .try_into()?)

```

2022-04-19 06:58 UTC, MartinJM commented
Hey, thanks for the review. I don't have much time to work on this for a while, so I'm not sure when I'll be able to make the changes. You should be able to write on this branch as well, feel free to make changes as you see fit.

I agree with your comments on the `length`, `search`, and `captures` functions.

The `hex_decode` functionality is indeed for an edge-case. There are some tools that output hex values when they encounter unicode. With a hex decode function this can easily be changed back into unicode.

2022-04-19 09:05 UTC, elkowar commented
Should there not be some other way to make these tools output stuff in the expected manner? Having a hex_decode function just to work around some specific weird tools seems weird, especially given that it should be easily possible to worst-case just pipe the output of said tool into some other hex-decoding shell utility and do it shell-wise

2022-04-19 11:20 UTC, elkowar commented
I pushed some fixes and rebased onto master, so this should be ready to merge now 👍🏻

2022-04-19 11:29 UTC, merged