Vanilla CSS support
elkowar/eww pull request #467
Opened 2022-05-31 00:08 UTC by EzequielRamis

## Description

Hi! This PR adds Vanilla CSS support, like said above. That's it.

## Additional Notes

The reason for this is that GTK CSS has its own quirks SCSS can't handle. It is not `grass` fault per se. I haven't read all the gtk docs, but one thing I've faced is how it [declares color variables](https://docs.gtk.org/gtk3/css-overview.html#an-example-for-defining-colors) using this little `@` char that breaks the SCSS compilation.

## Checklist

- [x] I added my changes to CHANGELOG.md, if appropriate.
- [x] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

2022-06-28 20:52 UTC, hannenz commented
I ran into the exact same issue, so I am looking forward to seeing this PR merged into main. I would really like to use use vanilla CSS alone for using @define-color declarations.

2023-01-05 19:10 UTC, elkowar requested changes
Sorry for the long wait! ^^'
This looks pretty good, I'd love to get this merged! Could you also rebase your changes onto latest master?

2023-01-05 19:10 UTC, elkowar commented on crates/eww/src/util.rs
> +        return Err(anyhow!("Encountered CSS and SCSS files together. Please consider using one of these."));
```suggestion
        return Err(anyhow!("Encountered both an SCSS and CSS file. Only one of these may exist at a time"));
```

2023-01-05 19:10 UTC, elkowar commented on crates/eww/src/util.rs
> +            std::fs::read_to_string(&css_file).with_context(|| format!("Given CSS File Doesnt Exist! {}", css_file.display()))?;
```suggestion
            std::fs::read_to_string(&css_file).with_context(|| format!("Given CSS file doesn't exist: {}", css_file.display()))?;
```

2023-01-05 19:10 UTC, elkowar commented on crates/eww/src/util.rs
> +        std::fs::read_to_string(&scss_file).with_context(|| format!("Given SCSS File Doesnt Exist! {}", scss_file.display()))?;
```suggestion
        std::fs::read_to_string(&scss_file).with_context(|| format!("Given SCSS file doesn't exist: {}", scss_file.display()))?;
```

2023-01-05 19:10 UTC, elkowar commented on docs/src/configuration.md
> +To get started, you'll need to create two files: `eww.yuck` and `eww.(s)css`.
```suggestion
To get started, you'll need to create two files: `eww.yuck` and `eww.scss` (or `eww.css`, if you prefer).
```

2023-01-08 02:27 UTC, EzequielRamis commented
No problem! 😁 there it is.

2023-02-25 09:35 UTC, merged