add get_env function to yuck
elkowar/eww pull request #779
Opened 2023-05-19 09:51 UTC by RegenJacob

## Description

This PR adds the function `get_env("KEY")` to yuck.
SCSS already has the ability to read env vars so adding it directly to yuck seemed nice

When the specified env var is empty it returns an empty string 

## Usage

```fennel
(label :text "${get_env("USER")}")
```

## Additional Notes

This needs more testing.

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [ ] All widgets I've added are correctly documented.
- [ ] I added my changes to CHANGELOG.md, if appropriate.
- [ ] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

2023-06-08 19:29 UTC, elkowar requested changes
Some slight cleanup, but otherwise this looks good!

2023-06-08 19:29 UTC, elkowar commented on docs/src/expression_language.md
> +    - `get_env(string)`: Gets the specified Enviroment variable
```suggestion
    - `get_env(string)`: Gets the specified environment variable
```

2023-06-08 19:29 UTC, elkowar commented on crates/simplexpr/src/eval.rs
> +        },
```suggestion
        "get_env" => match args.as_slice() {
            [var_name] => {
                let var = std::env::var(var_name.as_string()?).unwrap_or_default();
                Ok(DynVal::from(var))
            }
            _ => Err(EvalError::WrongArgCount(name.to_string())),
        },
```

2023-06-08 22:14 UTC, RegenJacob commented
I changed the code accordingly

2024-03-19 20:50 UTC, RegenJacob commented
Hi @elkowar ,

Just a friendly ping regarding this pull request submitted several months ago. It seems to be sitting idle despite being issue-free. If there are any concerns or additional steps needed, please let me know. Appreciate your attention to this.

2024-03-20 11:45 UTC, merged

2024-03-20 11:45 UTC, elkowar commented
Thanks for the ping, completely forgot to check this pr again! Thanks for your contribution!