Add jq_raw function to simplexpr
elkowar/eww pull request #952
Opened 2023-10-21 05:37 UTC by RomanHargrave

## Description
This is a fairly simple change which adds a `jq_raw` function - `jq_raw()` shares `jq()`'s implementation, with the difference being that _top level_ strings are not quoted (nested strings _are_ quoted). This behavior is consistent with `jq`'s documented and observed behavior for --raw-output.

This PR resolves #745.

For instance, we see the following behavior with orthodox `jq`

```
$ echo '{"a": ["b"]}' | jq -r '.a'
[
  "b"
]
$ echo '{"a": ["b"]}' | jq -r '.a[]'
b
```

Similarly, the expressions
```
{jq_raw("{\"a\": [\"b\"]}", ".a")}
{jq_raw("{\"a\": [\"b\"]}", ".a[]")}
```
Produce the following output,

![image](https://github.com/elkowar/eww/assets/6024227/e373b37e-ec47-470c-8856-275b28155da7)

## Usage

Use `jq_raw` as you would `jq` when unquoted strings are needed (typically for display)

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [X] All widgets I've added are correctly documented.
- [X] I added my changes to CHANGELOG.md, if appropriate.
- [X] The documentation in the `docs/src` directory has been adjusted to reflect my changes.
- [X] I used `cargo fmt` to automatically format all code before committing

2024-08-26 08:04 UTC, w-lfchen requested changes
looks good, just wrote down some thoughts to consider

2024-08-26 08:04 UTC, w-lfchen commented on crates/simplexpr/src/eval.rs
> +                serde_json::Value::String(contents) if raw_string => DynVal::from_string(contents),
```suggestion
                serde_json::Value::String(contents) if raw_output => DynVal::from_string(contents),
```

2024-08-26 08:04 UTC, w-lfchen commented on docs/src/expression_language.md
> +    - `jq_raw(value, jq_filter_string)`: as above, but top-level strings will not be quoted, as with `jq --raw-output`.
```suggestion
	- `jq(value, jq_filter_string)`: run a [jq](https://jqlang.github.io/jq/manual/) style command on a json value. (Uses [jaq](https://crates.io/crates/jaq) internally).
    - `jqraw(value, jq_filter_string)`: acts as if `jq` was invoked with the `--raw-output` flag, removing quotation marks if the resulting value is a JSON string. See the [jq docs](https://jqlang.github.io/jq/manual/) for more information.
```
point to the documentation here to make things easier for us

2024-12-29 20:24 UTC, elkowar commented
Closing this as it was implemented in #1199! Thanks a lot for you effort, and I apologize for the huge delay ._.

2024-12-29 20:24 UTC, closed without merging